import json, math, sys

# Hand-drawn surface map (32x32). '.' ocean, 'L' land, 'I' polar ice, 'C' cloud.
MAP = """
................................
................................
...........IIIIIIIII............
.........IIIIIIIIIIII...........
.......LLLL..IIIII..............
......LLLLLLL...LL..CCCCC.......
.....LLLLLLLLLLLLLL...CCCCC.....
....LLLLLLLLLLLLLL..............
....LLLLLLLLLLLLL...........LL..
....LLLLLLLLLLLL...........LLL..
.....LLLLLLLLLL...........LLLL..
......LLLLLLLL............LLLLL.
.......LLLLLL.............LLLLL.
........LLLL....CCCCC.....LLLLL.
.........LLL...CCCCCCC....LLLL..
..........LLL..............LLL..
...........LLLL............LL...
............LLLLL...............
............LLLLLLL.............
............LLLLLLLL............
.............LLLLLLL.....CCCC...
.............LLLLLL....CCCCCC...
..............LLLLL.............
..............LLLL..............
....CCCCC.....LLL...............
......CCCC.....LL...............
...............L................
................................
..........IIIIIIIIII............
...........IIIIIIII.............
................................
................................
""".strip().splitlines()

# 4-tone ramps: highlight, mid, shadow, deep shadow (hue-shifted toward blue/purple in shade)
RAMPS = {
    '.': ['#4fa4e8', '#2a6fc9', '#1d4796', '#142a5c'],
    'L': ['#8fd14f', '#4ea83a', '#2e7a36', '#1d4a2c'],
    'I': ['#ffffff', '#e4eef5', '#a9bdd1', '#6d7f9e'],
    'C': ['#ffffff', '#e4eef5', '#a9bdd1', '#6d7f9e'],
}
OUTLINE = '#0b1433'

CX, CY, R = 16.0, 16.0, 14.6
lx, ly, lz = -0.55, -0.55, 0.63
ln = math.sqrt(lx*lx + ly*ly + lz*lz)
lx, ly, lz = lx/ln, ly/ln, lz/ln

def inside(x, y):
    return (x + 0.5 - CX)**2 + (y + 0.5 - CY)**2 <= R*R

pixels = []
for y in range(32):
    for x in range(32):
        if inside(x, y):
            nx = (x + 0.5 - CX) / R
            ny = (y + 0.5 - CY) / R
            nz = math.sqrt(max(0.0, 1 - nx*nx - ny*ny))
            d = nx*lx + ny*ly + nz*lz
            tone = 0 if d > 0.85 else 1 if d > 0.45 else 2 if d > 0.1 else 3
            pixels.append({'x': x, 'y': y, 'color': RAMPS[MAP[y][x]][tone]})
        elif any(inside(x+dx, y+dy) for dx, dy in ((1,0),(-1,0),(0,1),(0,-1))):
            pixels.append({'x': x, 'y': y, 'color': OUTLINE})

half = sys.argv[1] if len(sys.argv) > 1 else 'all'
if half == 'top':
    pixels = [p for p in pixels if p['y'] < 16]
elif half == 'bottom':
    pixels = [p for p in pixels if p['y'] >= 16]
print(json.dumps(pixels, separators=(',', ':')))
